[package]
name = "echor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.x", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.96"
assert_cmd = "2.0.16"
predicates = "3.1.3"
pretty_assertions = "1.4.1"
